"""baseline schema

Issue #1028 (chunk 1/5, alembic-baseline). Reproduces the CURRENT schema —
every table Archimedes' 17 ORM models declare (``Base.metadata``, imported
in full by ``migrations/env.py``) — as of the adoption of Alembic. This is
what ``archimedes.db.init_db()``'s ``Base.metadata.create_all()`` already
produces on a fresh database today, generated here via
``alembic revision --autogenerate`` against an empty SQLite DB and verified
column-for-column identical to a fresh ``create_all()`` DB (see PR
description). It also applies cleanly against a fresh Postgres DB.

Supersedes the hand-rolled ``backend/migrations/*.sql`` files that
previously lived alongside this directory (11 files, 2026-05-18 →
2026-07-03) — those are historical record only from here forward; new
schema changes are Alembic revisions.

Two schema-management paths from here (per issue #1028's design decisions):
  - **Fresh / empty DB** (new dev clone, CI, tests): ``alembic upgrade head``
    runs this revision for real, OR ``init_db()``'s ``create_all()`` — both
    produce the identical schema, so either path is safe for tests.
  - **Already-populated prod Postgres** (schema already matches these models
    via the retiring create_all + idempotent-ALTER pattern in ``db.py``):
    stamp this revision as already-applied — ``alembic stamp af9c6a9376e4``
    (or ``alembic stamp head`` once this is the only revision) — then real
    ``alembic upgrade head`` runs for every revision after this one.

Revision ID: af9c6a9376e4
Revises:
Create Date: 2026-07-06 22:44:23.780517

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "af9c6a9376e4"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "backtest_results",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("strategy_id", sa.String(length=64), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=32), nullable=True),
        sa.Column("operation", sa.String(length=32), nullable=True),
        sa.Column("sharpe_ratio", sa.Float(), nullable=False),
        sa.Column("sortino_ratio", sa.Float(), nullable=False),
        sa.Column("max_drawdown", sa.Float(), nullable=False),
        sa.Column("cagr", sa.Float(), nullable=False),
        sa.Column("calmar_ratio", sa.Float(), nullable=False),
        sa.Column("win_rate", sa.Float(), nullable=False),
        sa.Column("profit_factor", sa.Float(), nullable=False),
        sa.Column("total_trades", sa.Integer(), nullable=False),
        sa.Column("avg_holding_period_days", sa.Float(), nullable=False),
        sa.Column("correlation_to_spy", sa.Float(), nullable=False),
        sa.Column("correlation_to_btc", sa.Float(), nullable=False),
        sa.Column("equity_curve_json", sa.Text(), nullable=False),
        sa.Column("monthly_returns_json", sa.Text(), nullable=False),
        sa.Column("backtest_start", sa.Date(), nullable=True),
        sa.Column("backtest_end", sa.Date(), nullable=True),
        sa.Column("paper_claimed_sharpe", sa.Float(), nullable=True),
        sa.Column("paper_claimed_cagr", sa.Float(), nullable=True),
        sa.Column("paper_claimed_max_dd", sa.Float(), nullable=True),
        sa.Column("deflated_sharpe_ratio", sa.Float(), nullable=True),
        sa.Column("dsr_p_value", sa.Float(), nullable=True),
        sa.Column("num_trials_in_selection", sa.Integer(), nullable=True),
        sa.Column("pbo_score", sa.Float(), nullable=True),
        sa.Column("out_of_sample_sharpe", sa.Float(), nullable=True),
        sa.Column("walk_forward_train_fraction", sa.Float(), nullable=False),
        sa.Column("look_ahead_audit_passed", sa.Boolean(), nullable=False),
        sa.Column("backtest_engine", sa.String(length=32), nullable=True),
        sa.Column("backtest_code_hash", sa.String(length=64), nullable=True),
        sa.Column("transaction_cost_bps", sa.Integer(), nullable=False),
        sa.Column("artifact_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("strategy_id", "content_hash", name="uq_backtest_strategy_content"),
    )
    with op.batch_alter_table("backtest_results", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_backtest_results_strategy_id"), ["strategy_id"], unique=False)
        batch_op.create_index("ix_backtest_strategy_created", ["strategy_id", "created_at"], unique=False)

    op.create_table(
        "chat_messages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("vault_address", sa.String(length=42), nullable=False),
        sa.Column("wallet_address", sa.String(length=42), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("is_ai", sa.Boolean(), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("chat_messages", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_chat_messages_vault_address"), ["vault_address"], unique=False)
        batch_op.create_index("ix_chat_vault_created", ["vault_address", "created_at"], unique=False)

    op.create_table(
        "corpus_meta",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("last_intake_at", sa.DateTime(), nullable=True),
        sa.Column("corpus_hash", sa.String(length=64), nullable=True),
        sa.Column("artifact_hash", sa.String(length=64), nullable=True),
        sa.Column("artifact_built_at", sa.DateTime(), nullable=True),
        sa.Column("paper_count", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "kg_entities",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("canonical_name", sa.String(), nullable=False),
        sa.Column("entity_type", sa.String(), nullable=False),
        sa.Column("paper_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("canonical_name", "entity_type", name="uq_kg_entity"),
    )
    with op.batch_alter_table("kg_entities", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_kg_entities_canonical_name"), ["canonical_name"], unique=False)

    op.create_table(
        "marketplace_agents",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("strategy_id", sa.String(length=128), nullable=False),
        sa.Column("creator_wallet", sa.String(length=42), nullable=False),
        sa.Column("subscriber_wallet", sa.String(length=42), nullable=False),
        sa.Column("sub_id", sa.String(length=66), nullable=False),
        sa.Column("pool_id", sa.String(length=66), nullable=False),
        sa.Column("vault_address", sa.String(length=42), nullable=False),
        sa.Column("ephemeral_wallet", sa.String(length=42), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("halted", sa.Boolean(), nullable=False),
        sa.Column("gateway_seller_address", sa.String(length=42), nullable=True),
        sa.Column("agent_wallet_id", sa.String(length=128), nullable=True),
        sa.Column("circle_wallet_id", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("stopped_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("marketplace_agents", schema=None) as batch_op:
        batch_op.create_index(
            "uq_marketplace_agents_running_publisher",
            ["role", "strategy_id"],
            unique=True,
            postgresql_where=sa.text("role = 'publisher' AND status = 'running'"),
            sqlite_where=sa.text("role = 'publisher' AND status = 'running'"),
        )
        batch_op.create_index(
            "uq_marketplace_agents_running_subscriber",
            ["role", "subscriber_wallet", "strategy_id"],
            unique=True,
            postgresql_where=sa.text("role = 'subscriber' AND status = 'running'"),
            sqlite_where=sa.text("role = 'subscriber' AND status = 'running'"),
        )
        batch_op.create_index(
            "uq_marketplace_agents_sub_id",
            ["sub_id"],
            unique=True,
            postgresql_where=sa.text("role = 'subscriber'"),
            sqlite_where=sa.text("role = 'subscriber'"),
        )

    op.create_table(
        "papers",
        sa.Column("arxiv_id", sa.String(length=32), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("authors", sa.Text(), nullable=False),
        sa.Column("abstract", sa.Text(), nullable=False),
        sa.Column("primary_category", sa.String(length=64), nullable=False),
        sa.Column("categories", sa.Text(), nullable=False),
        sa.Column("published", sa.String(length=32), nullable=False),
        sa.Column("updated", sa.String(length=32), nullable=False),
        sa.Column("pdf_url", sa.Text(), nullable=True),
        sa.Column("pdf_sha256", sa.String(length=64), nullable=True),
        sa.Column("full_text_path", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("cluster_id", sa.String(length=64), nullable=True),
        sa.Column("topic_label", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("ingested_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("arxiv_id"),
    )
    with op.batch_alter_table("papers", schema=None) as batch_op:
        batch_op.create_index("ix_papers_primary_category", ["primary_category"], unique=False)
        batch_op.create_index("ix_papers_published", ["published"], unique=False)

    op.create_table(
        "settlement_intents",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("strategy_id", sa.String(length=128), nullable=False),
        sa.Column("tick_id", sa.String(length=128), nullable=False),
        sa.Column("sub_id", sa.String(length=66), nullable=False),
        sa.Column("step", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("amount_usdc", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("settled_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("settlement_intents", schema=None) as batch_op:
        batch_op.create_index(
            "uq_settlement_intent_logical_charge", ["strategy_id", "tick_id", "sub_id", "step"], unique=True
        )

    op.create_table(
        "strategy_backtest_fixtures",
        sa.Column("stem", sa.String(length=128), nullable=False),
        sa.Column("n_obs_daily", sa.Integer(), nullable=False),
        sa.Column("sharpe_ratio", sa.Float(), nullable=False),
        sa.Column("sortino_ratio", sa.Float(), nullable=False),
        sa.Column("max_drawdown", sa.Float(), nullable=False),
        sa.Column("cagr", sa.Float(), nullable=False),
        sa.Column("calmar_ratio", sa.Float(), nullable=False),
        sa.Column("win_rate", sa.Float(), nullable=True),
        sa.Column("profit_factor", sa.Float(), nullable=True),
        sa.Column("total_trades", sa.Integer(), nullable=False),
        sa.Column("avg_holding_period_days", sa.Float(), nullable=True),
        sa.Column("correlation_to_spy", sa.Float(), nullable=False),
        sa.Column("correlation_to_btc", sa.Float(), nullable=True),
        sa.Column("out_of_sample_sharpe", sa.Float(), nullable=False),
        sa.Column("look_ahead_audit_passed", sa.Boolean(), nullable=False),
        sa.Column("backtest_engine", sa.String(length=64), nullable=False),
        sa.Column("transaction_cost_bps", sa.Integer(), nullable=False),
        sa.Column("backtest_start", sa.String(length=32), nullable=False),
        sa.Column("backtest_end", sa.String(length=32), nullable=False),
        sa.Column("paper_claimed_sharpe", sa.Float(), nullable=True),
        sa.Column("paper_claimed_cagr", sa.Float(), nullable=True),
        sa.Column("paper_claimed_max_dd", sa.Float(), nullable=True),
        sa.Column("deflated_sharpe_ratio", sa.Float(), nullable=False),
        sa.Column("dsr_p_value", sa.Float(), nullable=False),
        sa.Column("dsr_convention", sa.String(length=16), nullable=False),
        sa.Column("num_trials_in_selection", sa.Integer(), nullable=False),
        sa.Column("pbo_score", sa.Float(), nullable=False),
        sa.Column("passes_rigor_gate", sa.Boolean(), nullable=False),
        sa.Column("kelly_fraction", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("stem"),
    )
    op.create_table(
        "strategy_daily_returns",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("stem", sa.String(length=128), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("daily_return", sa.Float(), nullable=False),
        sa.Column("data_vintage", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stem", "date", name="uq_strategy_daily_returns_stem_date"),
    )
    with op.batch_alter_table("strategy_daily_returns", schema=None) as batch_op:
        batch_op.create_index("ix_strategy_daily_returns_stem", ["stem"], unique=False)

    op.create_table(
        "strategy_generators",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("strategy_id", sa.String(length=64), nullable=False),
        sa.Column("wallet_address", sa.String(length=42), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("strategy_id", "wallet_address", name="uq_strategy_generator"),
    )
    with op.batch_alter_table("strategy_generators", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_strategy_generators_strategy_id"), ["strategy_id"], unique=False)
        batch_op.create_index("ix_strategy_generators_strategy_wallet", ["strategy_id", "wallet_address"], unique=False)
        batch_op.create_index(batch_op.f("ix_strategy_generators_wallet_address"), ["wallet_address"], unique=False)

    op.create_table(
        "strategy_passports",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("methodology_hash", sa.String(length=64), nullable=True),
        sa.Column("content_hash", sa.String(length=66), nullable=True),
        sa.Column("generation_method", sa.String(length=32), nullable=False),
        sa.Column("methodology_summary", sa.Text(), nullable=False),
        sa.Column("methodology_text", sa.Text(), nullable=True),
        sa.Column("asset_universe", sa.Text(), nullable=False),
        sa.Column("universe_source", sa.String(length=16), nullable=True),
        sa.Column("position_sizing", sa.String(length=32), nullable=False),
        sa.Column("rebalance_frequency", sa.String(length=32), nullable=False),
        sa.Column("risk_constraints", sa.Text(), nullable=True),
        sa.Column("risk_profiles", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("regime_tag", sa.String(length=20), nullable=False),
        sa.Column("extraction_llm", sa.String(length=64), nullable=True),
        sa.Column("extraction_prompt_hash", sa.String(length=64), nullable=True),
        sa.Column("curator_wallet", sa.String(length=42), nullable=True),
        sa.Column("curator_note", sa.Text(), nullable=True),
        sa.Column("owner_wallet", sa.String(length=42), nullable=True),
        sa.Column("strategy_code_path", sa.String(length=512), nullable=True),
        sa.Column("strategy_code_hash", sa.String(length=64), nullable=True),
        sa.Column("on_chain_registration_tx", sa.String(length=66), nullable=True),
        sa.Column("on_chain_registration_block", sa.String(length=32), nullable=True),
        sa.Column("paper_claimed_sharpe", sa.Float(), nullable=True),
        sa.Column("paper_claimed_cagr", sa.Float(), nullable=True),
        sa.Column("paper_claimed_max_dd", sa.Float(), nullable=True),
        sa.Column("paper_claim_blended_sharpe", sa.Float(), nullable=True),
        sa.Column("sharpe_ratio", sa.Float(), nullable=True),
        sa.Column("sortino_ratio", sa.Float(), nullable=True),
        sa.Column("max_drawdown", sa.Float(), nullable=True),
        sa.Column("cagr", sa.Float(), nullable=True),
        sa.Column("win_rate", sa.Float(), nullable=True),
        sa.Column("total_trades", sa.Integer(), nullable=True),
        sa.Column("calmar_ratio", sa.Float(), nullable=True),
        sa.Column("correlation_to_spy", sa.Float(), nullable=True),
        sa.Column("backtest_start", sa.String(length=32), nullable=True),
        sa.Column("backtest_end", sa.String(length=32), nullable=True),
        sa.Column("deflated_sharpe_ratio", sa.Float(), nullable=True),
        sa.Column("dsr_p_value", sa.Float(), nullable=True),
        sa.Column("pbo_score", sa.Float(), nullable=True),
        sa.Column("out_of_sample_sharpe", sa.Float(), nullable=True),
        sa.Column("passes_rigor_gate", sa.Boolean(), nullable=False),
        sa.Column("kelly_fraction", sa.Float(), nullable=True),
        sa.Column("sharpe_ci_lower", sa.Float(), nullable=True),
        sa.Column("sharpe_ci_upper", sa.Float(), nullable=True),
        sa.Column("n_obs_daily", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("content_hash"),
    )
    with op.batch_alter_table("strategy_passports", schema=None) as batch_op:
        batch_op.create_index("ix_passport_method", ["generation_method"], unique=False)
        batch_op.create_index("ix_passport_regime", ["regime_tag"], unique=False)
        batch_op.create_index("ix_passport_status", ["status"], unique=False)

    op.create_table(
        "strategy_proposals",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("generation_id", sa.String(length=64), nullable=False),
        sa.Column("proposal_id", sa.String(length=64), nullable=False),
        sa.Column("parent_proposal_id", sa.String(length=64), nullable=True),
        sa.Column("verdict", sa.String(length=32), nullable=False),
        sa.Column("trust_level", sa.String(length=16), nullable=False),
        sa.Column("content_hash", sa.String(length=66), nullable=False),
        sa.Column("agent", sa.String(length=32), nullable=False),
        sa.Column("regime_tag", sa.String(length=16), nullable=True),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("content_hash"),
    )
    with op.batch_alter_table("strategy_proposals", schema=None) as batch_op:
        batch_op.create_index("ix_proposal_agent", ["agent"], unique=False)
        batch_op.create_index("ix_proposal_generation_id", ["generation_id"], unique=False)
        batch_op.create_index("ix_proposal_verdict", ["verdict"], unique=False)
        batch_op.create_index(batch_op.f("ix_strategy_proposals_generation_id"), ["generation_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_strategy_proposals_proposal_id"), ["proposal_id"], unique=False)

    op.create_table(
        "strategy_store",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("content_hash", sa.String(length=66), nullable=False),
        sa.Column("generation_method", sa.String(length=32), nullable=False),
        sa.Column("source_papers", sa.Text(), nullable=False),
        sa.Column("provenance_hash", sa.String(length=66), nullable=True),
        sa.Column("strategy_name", sa.String(length=256), nullable=False),
        sa.Column("thesis", sa.Text(), nullable=False),
        sa.Column("asset_universe", sa.Text(), nullable=False),
        sa.Column("risk_profile", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("rigor_verdict", sa.Text(), nullable=True),
        sa.Column("is_example", sa.Boolean(), nullable=False),
        sa.Column("owner_wallet", sa.String(length=42), nullable=True),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("on_chain_registration_tx", sa.String(length=66), nullable=True),
        sa.Column("on_chain_registration_block", sa.String(length=32), nullable=True),
        sa.Column("parent_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("content_hash", name="uq_strategy_content_hash"),
    )
    with op.batch_alter_table("strategy_store", schema=None) as batch_op:
        batch_op.create_index("ix_strategy_generation", ["generation_method"], unique=False)
        batch_op.create_index("ix_strategy_status", ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_strategy_store_owner_wallet"), ["owner_wallet"], unique=False)

    op.create_table(
        "subscriber_liabilities",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sub_id", sa.String(length=66), nullable=False),
        sa.Column("strategy_id", sa.String(length=128), nullable=False),
        sa.Column("tick_id", sa.String(length=128), nullable=False),
        sa.Column("action_count", sa.Integer(), nullable=False),
        sa.Column("unit_price_usdc", sa.Numeric(), nullable=True),
        sa.Column("amount_owed_usdc", sa.Numeric(), nullable=True),
        sa.Column("reason", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution_note", sa.String(length=512), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "subscriber_tick_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sub_id", sa.String(length=66), nullable=False),
        sa.Column("strategy_id", sa.String(length=128), nullable=False),
        sa.Column("tick_id", sa.String(length=128), nullable=False),
        sa.Column("step_reached", sa.String(length=32), nullable=False),
        sa.Column("halted", sa.Boolean(), nullable=False),
        sa.Column("halt_source", sa.String(length=16), nullable=True),
        sa.Column("halt_reason", sa.String(length=512), nullable=True),
        sa.Column("charged", sa.Boolean(), nullable=False),
        sa.Column("action_count", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("subscriber_tick_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_subscriber_tick_log_strategy_id"), ["strategy_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_subscriber_tick_log_sub_id"), ["sub_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_subscriber_tick_log_tick_id"), ["tick_id"], unique=False)

    op.create_table(
        "user_profiles",
        sa.Column("wallet_address", sa.String(length=42), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=True),
        sa.Column("email", sa.String(length=256), nullable=True),
        sa.Column("interests", sa.Text(), nullable=True),
        sa.Column("attribution", sa.String(length=256), nullable=True),
        sa.Column("marketing_opt_in", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("wallet_address"),
    )
    op.create_table(
        "vault_metadata",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("vault_address", sa.String(length=42), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("creator_address", sa.String(length=42), nullable=False),
        sa.Column("strategy_ids", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("vault_metadata", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_vault_metadata_vault_address"), ["vault_address"], unique=True)

    op.create_table(
        "kg_relations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("subject_id", sa.Integer(), nullable=True),
        sa.Column("relation", sa.String(), nullable=False),
        sa.Column("object_id", sa.Integer(), nullable=True),
        sa.Column("paper_arxiv_id", sa.String(), nullable=True),
        sa.Column("confidence", sa.REAL(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["object_id"],
            ["kg_entities.id"],
        ),
        sa.ForeignKeyConstraint(["paper_arxiv_id"], ["papers.arxiv_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["kg_entities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("subject_id", "relation", "object_id", "paper_arxiv_id", name="uq_kg_relation"),
    )
    with op.batch_alter_table("kg_relations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_kg_relations_paper_arxiv_id"), ["paper_arxiv_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_kg_relations_subject_id"), ["subject_id"], unique=False)

    op.create_table(
        "passport_paper_refs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("passport_id", sa.String(length=64), nullable=False),
        sa.Column("arxiv_id", sa.String(length=32), nullable=True),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("authors", sa.Text(), nullable=True),
        sa.Column("doi", sa.String(length=128), nullable=True),
        sa.Column("venue", sa.String(length=256), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("citation_count", sa.Integer(), nullable=True),
        sa.Column("contribution", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["passport_id"], ["strategy_passports.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("passport_paper_refs")
    with op.batch_alter_table("kg_relations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_kg_relations_subject_id"))
        batch_op.drop_index(batch_op.f("ix_kg_relations_paper_arxiv_id"))

    op.drop_table("kg_relations")
    with op.batch_alter_table("vault_metadata", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_vault_metadata_vault_address"))

    op.drop_table("vault_metadata")
    op.drop_table("user_profiles")
    with op.batch_alter_table("subscriber_tick_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_subscriber_tick_log_tick_id"))
        batch_op.drop_index(batch_op.f("ix_subscriber_tick_log_sub_id"))
        batch_op.drop_index(batch_op.f("ix_subscriber_tick_log_strategy_id"))

    op.drop_table("subscriber_tick_log")
    op.drop_table("subscriber_liabilities")
    with op.batch_alter_table("strategy_store", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_strategy_store_owner_wallet"))
        batch_op.drop_index("ix_strategy_status")
        batch_op.drop_index("ix_strategy_generation")

    op.drop_table("strategy_store")
    with op.batch_alter_table("strategy_proposals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_strategy_proposals_proposal_id"))
        batch_op.drop_index(batch_op.f("ix_strategy_proposals_generation_id"))
        batch_op.drop_index("ix_proposal_verdict")
        batch_op.drop_index("ix_proposal_generation_id")
        batch_op.drop_index("ix_proposal_agent")

    op.drop_table("strategy_proposals")
    with op.batch_alter_table("strategy_passports", schema=None) as batch_op:
        batch_op.drop_index("ix_passport_status")
        batch_op.drop_index("ix_passport_regime")
        batch_op.drop_index("ix_passport_method")

    op.drop_table("strategy_passports")
    with op.batch_alter_table("strategy_generators", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_strategy_generators_wallet_address"))
        batch_op.drop_index("ix_strategy_generators_strategy_wallet")
        batch_op.drop_index(batch_op.f("ix_strategy_generators_strategy_id"))

    op.drop_table("strategy_generators")
    with op.batch_alter_table("strategy_daily_returns", schema=None) as batch_op:
        batch_op.drop_index("ix_strategy_daily_returns_stem")

    op.drop_table("strategy_daily_returns")
    op.drop_table("strategy_backtest_fixtures")
    with op.batch_alter_table("settlement_intents", schema=None) as batch_op:
        batch_op.drop_index("uq_settlement_intent_logical_charge")

    op.drop_table("settlement_intents")
    with op.batch_alter_table("papers", schema=None) as batch_op:
        batch_op.drop_index("ix_papers_published")
        batch_op.drop_index("ix_papers_primary_category")

    op.drop_table("papers")
    with op.batch_alter_table("marketplace_agents", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_marketplace_agents_sub_id",
            postgresql_where=sa.text("role = 'subscriber'"),
            sqlite_where=sa.text("role = 'subscriber'"),
        )
        batch_op.drop_index(
            "uq_marketplace_agents_running_subscriber",
            postgresql_where=sa.text("role = 'subscriber' AND status = 'running'"),
            sqlite_where=sa.text("role = 'subscriber' AND status = 'running'"),
        )
        batch_op.drop_index(
            "uq_marketplace_agents_running_publisher",
            postgresql_where=sa.text("role = 'publisher' AND status = 'running'"),
            sqlite_where=sa.text("role = 'publisher' AND status = 'running'"),
        )

    op.drop_table("marketplace_agents")
    with op.batch_alter_table("kg_entities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_kg_entities_canonical_name"))

    op.drop_table("kg_entities")
    op.drop_table("corpus_meta")
    with op.batch_alter_table("chat_messages", schema=None) as batch_op:
        batch_op.drop_index("ix_chat_vault_created")
        batch_op.drop_index(batch_op.f("ix_chat_messages_vault_address"))

    op.drop_table("chat_messages")
    with op.batch_alter_table("backtest_results", schema=None) as batch_op:
        batch_op.drop_index("ix_backtest_strategy_created")
        batch_op.drop_index(batch_op.f("ix_backtest_results_strategy_id"))

    op.drop_table("backtest_results")
    # ### end Alembic commands ###
